---
version: "3"

services:
  e2e:
    image: "cypress/included:7.3.0"
    depends_on:
      - frontend
    environment:
      - CYPRESS_baseUrl=http://frontend:3000
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e
